id: 8db1f963c96248b791ceb5c0ac4b1df8
initial_creation_type: ocr
source_metadata:
  volumes:
    5c459a3c12f2432bb234e52bf40ef09d:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ''
      total_pages: 1539
      volume_number: 1
